### ISSUE TITLE
Missing RSS feed for your blog

### ISSUE THREAD

**Issue by r00t-is-g00d** [khang06/khang06.github.io#1]
Your writing and technical skills are excellent! It would be better if you could add RSS feed to your blog so I can subscribe to your new posts 😄 

Just curious, are you Vietnamese 🇻🇳 ?

**Comment by khang06** [comment]
should be fixed in bfd2408a2665d038cf0e51ea9f0f822585b3c8e8. also, yes, i'm vietnamese. probably obvious from my name

btw, just curious, how'd you find this blog post? seems like it randomly got a lot of attention weeks after i wrote it but i don't have (nor do i want to set up) any analytics so i have no idea what happened

**Comment by r00t-is-g00d** [comment]
@khang06, I found your blog on X (former Twitter). I'm also Vietnamese, I have a group on Discord that focuses on security stuff. Would you like to join the server? 

The server is new, I'm looking for new members 😁Here is the link: https://discord.gg/d9SWFvvY
